name: gistracker
description: Simple GIS Tracker for collecting tracks and points 

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 0.0.1+1

environment:
  sdk: '>=3.2.0-0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  flutter_background_service_platform_interface: ^5.0.0
  flutter_map: ^6.1.0
  flutter_map_location_marker: ^8.0.8
  flutter_map_tile_caching: ^9.0.0
  geolocator: ^11.0.0
  gpx: ^2.2.2
  intl: ^0.19.0
  latlong2: ^0.9.1
  path_provider: ^2.1.3
# dev_dependencies:
#   flutter_test:
#     sdk: flutter

#   flutter_lints: ^3.0.2

flutter:
  uses-material-design: true
